import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router';
import React, { useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const router = useRouter();

  const handleFinancasClick = () => {
    router.push('/financas');
  }

  const handlerelatoriosClick = () => {
    router.push('/relatorio');
  };

  const handleEstatisticaClick = () => {
    router.push('/estatistica');
  }

  const handleConsultoriaClick = () => {
    router.push('/consultoria');
  }

  const [messages, setMessages] = useState<string[]>([]);
  
  const handleMessageSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const message = e.currentTarget.message.value;
    setMessages([...messages, message]);
    e.currentTarget.message.value = '';
  };
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <ul className={styles.menu}>
          <li>
            <a onClick={handleFinancasClick}>+Finanças</a>
          </li>
          <li>
            <a onClick={handlerelatoriosClick}>relatorios</a>
          </li>
          <li>
            <a onClick={handleEstatisticaClick}>Estátistica</a>
          </li>
          <li>
            <a onClick={handleConsultoriaClick}>Consultoria</a>
          </li>
        </ul>

        <a href="http://chatbotmaisfinancas.infinityfreeapp.com/">
          <div className={styles.Bot}>
            CHATBOT
          </div>
        </a>
      
      </main>
    </>
  );
}
