import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router';
import React from 'react';
import PieChart from '@/pages/PieChart';
import LineChart from '@/pages/LineChart';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const router = useRouter();

  const handleFinancasClick = () => {
    router.push('/financas');
  }

  const handleMenuClick = () => {
    router.push('/menu');
  };

  const handleEstatisticaClick = () => {
    router.push('/estatistica');
  }

  const handleConsultoriaClick = () => {
    router.push('/consultoria');
  }

  const chartData = {
    labels: ['Essenciais', 'Lazer', 'Reserva'],
    values: [10.000, 7.320, 2.670],
  };

  const data = {
    labels: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun'],
    values: [100, 150, 200, 120, 180, 90],
  };

  
  return (

    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <ul className={styles.menu}>
          <li>
            <a onClick={handleFinancasClick}>+Finanças</a>
          </li>
          <li>
            <a onClick={handleMenuClick}>Menu</a>
          </li>
          <li>
            <a onClick={handleEstatisticaClick}>Estátistica</a>
          </li>
          <li>
            <a onClick={handleConsultoriaClick}>Consultoria</a>
          </li>
        </ul>

        <div className={styles.GraficoRosca}>
            <h1>Gestão de Gastos</h1>
            <PieChart data={chartData} />
        </div>
           
        <div className={styles.GraficoLinha}>
            <h1>Gastos</h1>
            <LineChart data={data} />
        </div>


      </main>
    </>
  );
}
