import React, { useState, useEffect } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router';
import { Colors } from 'chart.js';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const router = useRouter();
  const [gastoMensal, setGastoMensal] = useState(null);
  const [mesAtual, setMesAtual] = useState('');

  useEffect(() => {
    const fetchGastoMensal = async () => {
      try {
        const response = await fetch('http://localhost:8080/gastos-do-mes-atual');
        const data = await response.json();
        
        const somaGastos = data.gastosDoMesAtual.reduce((total, gasto) => total + gasto.Valor, 0);

        setGastoMensal(somaGastos);
      } catch (error) {
        console.error('Erro ao obter gastos mensais:', error.message);
      }
    };

    const obterMesAtual = () => {
      const meses = [
        'Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho',
        'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'
      ];

      const agora = new Date();
      const nomeMesAtual = meses[agora.getMonth()];

      setMesAtual(nomeMesAtual);
    };

    fetchGastoMensal();
    obterMesAtual();
  }, []);

  const handleFinancasClick = () => {
    router.push('/financas');
  }

  const handleMenuClick = () => {
    router.push('/menu');
  };

  const handleEstatisticaClick = () => {
    router.push('/estatistica');
  }

  const handleConsultoriaClick = () => {
    router.push('/consultoria');
  }

  const handleDespesaClick = () => {
    router.push('/novadespesa');
  }
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <ul className={styles.menu}>
          <li>
            <a onClick={handleFinancasClick}>+Finanças</a>
          </li>
          <li>
            <a onClick={handleMenuClick}>Menu</a>
          </li>
          <li>
            <a onClick={handleEstatisticaClick}>Estátistica</a>
          </li>
          <li>
            <a onClick={handleConsultoriaClick}>Consultoria</a>
          </li>
        </ul>

        <div className={styles.DivGastoMensal}>
            <h3>Gasto Mensal</h3>
            <h1>R$: {gastoMensal !== null ? gastoMensal.toFixed(2) : 'Carregando...'}</h1>
            <br></br>
            <a href="#"><h5>Ver Detalhes</h5></a>
        </div>

        <div className={styles.DivCarteiraDisponivel}>
            <div className={styles.Textos}>
                <h5>Carteira Disponível em {mesAtual}</h5>
                <br></br>
                <h6>Dinheiro Disponível</h6>
            </div>
            <div className={styles.Dinheiro}>
                <h1>R$: 21,230</h1>
            </div>
        </div>

        <div className={styles.DivObjetivos}>
            <div className={styles.Textos}>
                <h3>Objetivos</h3>
                <h4>Confira seus Objetivos</h4>
            </div>
            <div className={styles.Dinheiro}>
                <a href="#"><Image src="/icons8-casa-24.png" alt="Home" width={24} height={24}/></a>
            </div>
        </div>

        <div className={styles.Container}>
            <div className={styles.TituloDiv}>
                <h2>Tranferências da Semana</h2>
            </div>
            <div className={styles.DivCentralizada}>
                <div className={styles.Div1}>
                    <div className={styles.BolaVerde}></div>
                    <h3>$2,100.00</h3>
                    <h4>Ganhos</h4>
                </div>
                <div className={styles.Div2}>
                    <div className={styles.BolaVermelha}></div>
                    <h3>${gastoMensal !== null ? gastoMensal.toFixed(2) : 'Carregando...'}</h3>
                    <h4>Despesas</h4>
                </div>
            </div>
        </div>

        <div className={styles.addDespesa}>
          <a onClick={handleDespesaClick}>
            <Image className={styles.ButonAddDespesa} src="/add-button.svg" alt="Add Despesa" width={70} height={70}/>
            <h5 className={styles.TextDespesa}>Add Despesa</h5>
          </a>
        </div>
      </main>
    </>
  );
}
