import styles from '@/styles/Login.module.css'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useState } from 'react'

interface User {
  id: string
  nome: string
  email: string
}

export default function Login() {
  const router = useRouter()

  const [email, setEmail] = useState('')
  const [senha, setSenha] = useState('')
  const [error, setError] = useState('')

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault()

    try {
      console.log(email)
      console.log(
        JSON.stringify({
          email: email,
          senha: senha,
        })
      )

      const response = await fetch(
        'https://mais-financas-api.onrender.com/api/auth/login',
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            email: email,
            senha: senha,
          }),
        }
      )

      if (!response.ok) {
        throw new Error('Credenciais inválidas')
      }

      const user: User = await response.json()
      router.push(`/financas/${user.id}`)
    } catch (error: any) {
      setError(error.message || 'Erro desconhecido')
    }
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.h1}>Entre com a sua Conta</h1>
        <div>
          <Image
            src='/Dinheiro.png'
            alt='Cartiera de Dinheiro'
            width={100}
            height={100}
            className={styles.image}
          />
        </div>

        <form className={styles.form} onSubmit={handleLogin}>
          <div className={styles.formGroup}>
            <label className={styles.label}>
              Email:
              <input
                className={styles.input}
                type='text'
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
            </label>
          </div>

          <br />
          <div>
            <label className={styles.label}>
              Senha:
              <input
                className={styles.input}
                type='password'
                value={senha}
                onChange={(e) => setSenha(e.target.value)}
              />
            </label>
          </div>

          <br />
          <button type='submit' className={styles.button}>
            Login
          </button>
          {error && <p style={{ color: 'red' }}>{error}</p>}
        </form>
      </main>
    </>
  )
}
